# [K] (c) 2020

name: TEST

on:
  push:
    branches:
      - test
    paths:
      - '.github/workflows/master.yml'

jobs:
  create:

    runs-on: ubuntu-latest
    if: github.repository == 'kongfl888/lede'
    steps:

    - name: Checkout
      uses: actions/checkout@main
      with:
        ref: master
        fetch-depth: 0
        lfs: true

    - name: Set git identity
      run : |
        git config --global user.email "kongfl888@outlook.com"
        git config --global user.name "kongfl888 K"
    - name: Git Init
      run:  |
        git checkout test
        git branch -f master e0c345df71ee9555f20235a6eaa35fd70b0ab3eb
        git checkout master
        rm -rf .github/workflows
        git add .
        git commit -m "Remove workflows" || echo ""
        #mkdir -p .github/workflows
        #wget -O ./.github/workflows/test.yml https://raw.githubusercontent.com/kongfl888/lede/test/.github/workflows/Merge-upstream.yml
        #sed '/push:/,+6d' .github/workflows/test.yml
        #git add .
        #git commit -m "Add test"
    - name: Push Commits
      env:
        DOWNSTREAM_BRANCH: master
      run:  |
        git push --force origin $DOWNSTREAM_BRANCH
