# [K] (c) 2020

name: TEST

on:
  push:
    branches:
      - test
    paths:
      - '.github/workflows/master.yml'

jobs:
  create:

    runs-on: ubuntu-latest
    if: github.repository == 'kongfl888/lede'
    steps:

    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: test

    - name: Set git identity
      run : |
        git config --global user.email "kongfl888@outlook.com"
        git config --global user.name "kongfl888 K"
    - name: Git Init
      run:  |
        git remote add lean https://github.com/coolsnowwolf/lede.git
        git fetch lean master
        git branch master || echo ""
        git checkout master
        git reset master --hard lean/master
    - name: Push Commits
      env:
        DOWNSTREAM_BRANCH: master
      run:  |
        git push --force-with-lease origin $DOWNSTREAM_BRANCH
