# [K] (c) 2020

name: TEST

on:
  push:
    branches:
      - test
    paths:
      - '.github/workflows/master.yml'

jobs:
  create:

    runs-on: ubuntu-latest
    if: github.repository == 'kongfl888/lede'
    steps:

    - name: Checkout
      uses: actions/checkout@main
      with:
        ref: master
        fetch-depth: 0
        lfs: true

    - name: Set git identity
      run : |
        git config --global user.email "kongfl888@outlook.com"
        git config --global user.name "kongfl888 K"
    - name: Git Init
      run:  |
        git branch -f master e0c345df71ee9555f20235a6eaa35fd70b0ab3eb
        rm -rf .github/workflows
        git add .
        git commit -m "Remove workflows"
    - name: Push Commits
      env:
        DOWNSTREAM_BRANCH: master
      run:  |
        git push --force-with-lease origin $DOWNSTREAM_BRANCH
