# [K] (c) 2020

name: TEST

on:
  schedule:
    - cron: '10 */8 * * *'

jobs:
  merge:

    runs-on: ubuntu-latest
    if: github.repository == 'kongfl888/lede'
    steps:

    - name: Checkout
      uses: actions/checkout@main
      with:
        ref: test
        fetch-depth: 0
        lfs: true

    - name: Set git identity
      run : |
        git config --global user.email "kongfl888@outlook.com"
        git config --global user.name "kongfl888 K"
    - name: Load upstream commits
      run:  |
        git checkout test
        #cp -f ./scripts/apply.sh /tmp/apply-le.sh
        cp -rf ./r2s-patches-new /tmp
        git branch nanopi-r2s || echo ""
        git checkout nanopi-r2s
        git remote add lean https://github.com/coolsnowwolf/lede.git
        git fetch lean master
        git reset --hard lean/master
        #. /tmp/apply-le.sh
        git am --whitespace=fix /tmp/r2s-patches-new/*.patch
        rm -rf .github/workflows
        git add .
        git commit -m "Remove workflows"
    - name: Push Commits
      env:
        DOWNSTREAM_BRANCH: nanopi-r2s
      run:  |
        git push --force-with-lease origin $DOWNSTREAM_BRANCH
